package POJOs;
// Generated Sep 24, 2013 9:20:03 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.OneToMany;

/**
 * Donhang generated by hbm2java
 */

public class Donhang  implements java.io.Serializable {

     private int madonhang;
     private Khachhang khachhang;
     private Date ngaylap;
     private Double tongtien;
     private Set<Chitietdonhang> chitietdonhangs = new HashSet<Chitietdonhang>(0);

    public Donhang() {
    }

	
    public Donhang(int madonhang) {
        this.madonhang = madonhang;
    }
    public Donhang(int madonhang, Khachhang khachhang, Date ngaylap, Double tongtien, Set<Chitietdonhang> chitietdonhangs) {
       this.madonhang = madonhang;
       this.khachhang = khachhang;
       this.ngaylap = ngaylap;
       this.tongtien = tongtien;
       this.chitietdonhangs = chitietdonhangs;
    }
   
    public int getMadonhang() {
        return this.madonhang;
    }
    
    public void setMadonhang(int madonhang) {
        this.madonhang = madonhang;
    }
    public Khachhang getKhachhang() {
        return this.khachhang;
    }
    
    public void setKhachhang(Khachhang khachhang) {
        this.khachhang = khachhang;
    }
    public Date getNgaylap() {
        return this.ngaylap;
    }
    
    public void setNgaylap(Date ngaylap) {
        this.ngaylap = ngaylap;
    }
    public Double getTongtien() {
        return this.tongtien;
    }
    
    public void setTongtien(Double tongtien) {
        this.tongtien = tongtien;
    }
    
    public Set<Chitietdonhang> getChitietdonhangs() {
        return this.chitietdonhangs;
    }
    
    public void setChitietdonhangs(Set<Chitietdonhang> chitietdonhangs) {
        this.chitietdonhangs = chitietdonhangs;
    }




}


