package POJOs;
// Generated Sep 24, 2013 9:20:03 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Khachhang generated by hbm2java
 */
public class Khachhang  implements java.io.Serializable {


     private int makhachhang;
     private String hoten;
     private Integer gioitinh;
     private String email;
     private Date ngaysinh;
     private Integer trangthai;
     private Set<Donhang> donhangs = new HashSet<Donhang>(0);

    public Khachhang() {
    }

	
    public Khachhang(int makhachhang) {
        this.makhachhang = makhachhang;
    }
    public Khachhang(int makhachhang, String hoten, Integer gioitinh, String email, Date ngaysinh, Integer trangthai, Set<Donhang> donhangs) {
       this.makhachhang = makhachhang;
       this.hoten = hoten;
       this.gioitinh = gioitinh;
       this.email = email;
       this.ngaysinh = ngaysinh;
       this.trangthai = trangthai;
       this.donhangs = donhangs;
    }
   
    public int getMakhachhang() {
        return this.makhachhang;
    }
    
    public void setMakhachhang(int makhachhang) {
        this.makhachhang = makhachhang;
    }
    public String getHoten() {
        return this.hoten;
    }
    
    public void setHoten(String hoten) {
        this.hoten = hoten;
    }
    public Integer getGioitinh() {
        return this.gioitinh;
    }
    
    public void setGioitinh(Integer gioitinh) {
        this.gioitinh = gioitinh;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public Date getNgaysinh() {
        return this.ngaysinh;
    }
    
    public void setNgaysinh(Date ngaysinh) {
        this.ngaysinh = ngaysinh;
    }
    public Integer getTrangthai() {
        return this.trangthai;
    }
    
    public void setTrangthai(Integer trangthai) {
        this.trangthai = trangthai;
    }
    public Set<Donhang> getDonhangs() {
        return this.donhangs;
    }
    
    public void setDonhangs(Set<Donhang> donhangs) {
        this.donhangs = donhangs;
    }




}


